name: pyspark_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openjdk=11
  - pyspark=3.5.1
  - numpy
  - pandas
  - jupyter
  - notebook
  - pip:
    - findspark
    - matplotlib
    - seaborn
    - scikit-learn
    - xgboost